# Generated by Django 5.2.4 on 2025-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0008_colaborador_complemento_alter_colaborador_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='estado_vota',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado onde vota'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(choices=[('almoxarifado', 'Almoxarifado'), ('ambulatorio', 'Ambulatório'), ('bloco_cirurgico', 'Bloco Cirúrgico'), ('ccih', 'CCIH'), ('clinica_cirurgica', 'Clínica Cirúrgica'), ('clinica_ortopedica', 'Clínica Ortopédica'), ('epidemiologia', 'Epidemiologia'), ('farmacia', 'Farmácia'), ('imobilizacao', 'Imobilização'), ('maternidade', 'Maternidade'), ('recepcao', 'Recepção'), ('same', 'SAME'), ('uti', 'UTI')], default='enfermaria', max_length=100, verbose_name='Setor de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('licenca', 'Licença Premium')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral'), ('diarista', 'Diarista')], default='manha', max_length=100, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(max_length=20, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_ctps',
            field=models.CharField(max_length=20, verbose_name='UF da CTPS'),
        ),
    ]
