# Generated by Django 5.2.4 on 2025-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0009_alter_colaborador_estado_vota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('licenca', 'Licença Premium'), ('demitido', 'Demitido')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
