# Generated by Django 5.2.4 on 2025-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0010_alter_colaborador_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('medico', 'Médico'), ('analista', 'Analista em Saúde'), ('assistente', 'Assistente em Saúde'), ('auxiliar', 'Auxiliar em Saúde')], default='aux_admin', max_length=255, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(max_length=255, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(max_length=255, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(max_length=255, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(max_length=255, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='dias_trabalho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dias de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='documento_militar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Documento militar'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], default='solteiro', max_length=255, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_vota',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado onde vota'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(max_length=255, verbose_name='Função Específica'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='grau_instrucao',
            field=models.CharField(max_length=255, verbose_name='Grau de instrução'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='jornada_trabalho',
            field=models.CharField(max_length=255, verbose_name='Jornada de trabalho (Ex: 8h/dia)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(max_length=255, unique=True, verbose_name='Matrícula (código funcional)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(max_length=255, verbose_name='Naturalidade (cidade/estado)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_conselho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do conselho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(max_length=255, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(max_length=255, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_conselho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do conselho profissional'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_ctps',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_pasep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do PASEP'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='observacoes',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Observações (informações adicionais)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg_completo',
            field=models.CharField(max_length=255, verbose_name='RG (Número e órgão emissor)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='secao_eleitoral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seção eleitoral'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='serie_ctps',
            field=models.CharField(max_length=255, verbose_name='Série da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(choices=[('almoxarifado', 'Almoxarifado'), ('ambulatorio', 'Ambulatório'), ('bloco_cirurgico', 'Bloco Cirúrgico'), ('ccih', 'CCIH'), ('clinica_cirurgica', 'Clínica Cirúrgica'), ('clinica_ortopedica', 'Clínica Ortopédica'), ('epidemiologia', 'Epidemiologia'), ('farmacia', 'Farmácia'), ('imobilizacao', 'Imobilização'), ('maternidade', 'Maternidade'), ('recepcao', 'Recepção'), ('same', 'SAME'), ('uti', 'UTI'), ('dp', 'Departamento Pessoal')], default='enfermaria', max_length=255, verbose_name='Setor de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('licencan', 'Licença Nojo'), ('licencag', 'Licença Gala'), ('licencam', 'Licença Maternidade'), ('licencap', 'Licença Paternidade'), ('licencae', 'Licença Eleitoral'), ('licencat', 'Licença de Trato e Interesse Particular'), ('licencaedu', 'Licença Estudo'), ('licencapremio', 'Licença Prêmio'), ('demitido', 'Demitido'), ('exonerado', 'Exonerado')], default='ativo', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone fixo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(max_length=255, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de eleitor'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral'), ('diarista', 'Diarista')], default='manha', max_length=255, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(max_length=255, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_conselho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF do conselho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_ctps',
            field=models.CharField(max_length=255, verbose_name='UF da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='zona_eleitoral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zona eleitoral'),
        ),
    ]
