# Generated by Django 5.2.4 on 2025-08-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_ses_management', '0011_alter_colaborador_bairro_alter_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, choices=[('medico', 'Médico'), ('analista', 'Analista em Saúde'), ('assistente', 'Assistente em Saúde'), ('auxiliar', 'Auxiliar em Saúde')], default='aux_admin', max_length=255, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], default='solteiro', max_length=255, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Função Específica'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='grau_instrucao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grau de instrução'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='jornada_trabalho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jornada de trabalho (Ex: 8h/dia)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Matrícula (código funcional)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naturalidade (cidade/estado)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='numero_ctps',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rg_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RG (Número e órgão emissor)'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='serie_ctps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Série da CTPS'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor_trabalho',
            field=models.CharField(blank=True, choices=[('almoxarifado', 'Almoxarifado'), ('ambulatorio', 'Ambulatório'), ('bloco_cirurgico', 'Bloco Cirúrgico'), ('ccih', 'CCIH'), ('clinica_cirurgica', 'Clínica Cirúrgica'), ('clinica_ortopedica', 'Clínica Ortopédica'), ('epidemiologia', 'Epidemiologia'), ('farmacia', 'Farmácia'), ('imobilizacao', 'Imobilização'), ('maternidade', 'Maternidade'), ('recepcao', 'Recepção'), ('same', 'SAME'), ('uti', 'UTI'), ('dp', 'Departamento Pessoal')], default='enfermaria', max_length=255, null=True, verbose_name='Setor de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('ferias', 'Férias'), ('afastado', 'Afastado'), ('licencan', 'Licença Nojo'), ('licencag', 'Licença Gala'), ('licencam', 'Licença Maternidade'), ('licencap', 'Licença Paternidade'), ('licencae', 'Licença Eleitoral'), ('licencat', 'Licença de Trato e Interesse Particular'), ('licencaedu', 'Licença Estudo'), ('licencapremio', 'Licença Prêmio'), ('demitido', 'Demitido'), ('exonerado', 'Exonerado')], default='ativo', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='turno',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral'), ('diarista', 'Diarista')], default='manha', max_length=255, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='uf_ctps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UF da CTPS'),
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to='dp_ses_management.colaborador')),
            ],
        ),
    ]
